server:
  port: 9898
spring:
  redis:
    cluster:
      nodes: IP1:PORT1,IP2:PORT2
    password: xxxx
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
